/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BunnyGame (https://sketchfab.com/bunnyGame)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cheese-4470d6127021419c9308cddd5f4abecf
Title: Cheese
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function CheeseAvatar(props) {
  const { nodes, materials } = useGLTF('/models/cheese.glb')
  const modelRef = useRef()

  useFrame((state, delta, xrFrame) => {
      modelRef.current.position.y = -0.75 + Math.sin(state.clock.elapsedTime) * 0.15;
  })

  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[0,0,0]}
    scale={[1,1,1]}
    rotation={[-1.5,0,0.4]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/cheese.glb')
