/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tiko (https://sketchfab.com/tikoavp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cheese-moon-7cbba11da66245329aaff0cba3896b2b
Title: Cheese Moon
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export default function CheeseMoon(props) {
    const { nodes, materials } = useGLTF('/models/cheese_moon.glb');

    const modelRef = useRef()

    useFrame((state, delta, xrFrame) => {
        modelRef.current.position.y = Math.sin(state.clock.elapsedTime) * 0.15;
    })

    return (
        <group {...props} dispose={null}
            ref={modelRef}
            position={[0,0,0]}
            scale={[0.5, 0.5, 0.5]}
            rotation={[0, 0.2, 0.4]}
        >
            <group scale={0.01}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Moon001_Cheese_0.geometry}
                    material={materials.Cheese}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/cheese_moon.glb')
